# Generated by Django 4.2.3 on 2023-09-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_location_jobpost_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
